REM サブルーチンを含めたリンク：サブルーチンは固定

DEL %1.ABS
asm38 %1.asm
ECHO OFF
ECHO INPUT %1.OBJ > %1.SUB

REM 取り込むサブルーチン：先にアセンブルしておくこと
ECHO INPUT PCII_LCD_SG12864.OBJ >> %1.SUB
ECHO INPUT PCII_IRQ.OBJ >> %1.SUB
ECHO INPUT PCII_SCI3.OBJ >> %1.SUB
ECHO INPUT PCII_DATA.OBJ >> %1.SUB
ECHO INPUT PCII_AD.OBJ >> %1.SUB
ECHO INPUT PCII_LAP.OBJ >> %1.SUB
ECHO INPUT PCII_SETTING.OBJ >> %1.SUB
ECHO INPUT PCII_I2C.OBJ >> %1.SUB
ECHO INPUT PCII_I2C_VL53L0X.OBJ >> %1.SUB
ECHO INPUT PCII_I2C_EEPROM.OBJ >> %1.SUB
ECHO INPUT SUBS.OBJ >> %1.SUB

ECHO PRINT %1.MAP >> %1.SUB
ECHO OUTPUT %1.ABS >> %1.SUB
ECHO START INT_VECT(0), ROM, CONST(00034), INT_CODE(07000), VRAM(0F780), PDATA(0FB80) >> %1.SUB
ECHO EXIT >> %1.SUB
ECHO ON
lnk -SUBCOMMAND=%1.SUB
